version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building application"
      - npm run build || echo "No build step"

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
 