version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
      # This fixes the "Unsupported engine" error - your packages require Node 20+
      
  pre_build:
    commands:
      - echo Installing dependencies...
      - node --version
      - npm --version
      # Use 'npm install' instead of 'npm ci' to handle lock file sync issues
      - npm install
      
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo Build completed on `date`
      
  post_build:
    commands:
      - echo Build finished

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  
cache:
  paths:
    - 'node_modules/**/*'