version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      
  pre_build:
    commands:
      - echo Installing dependencies...
      - node --version
      - npm --version
      # Delete package-lock.json and reinstall everything fresh
      - rm -f package-lock.json
      - npm install
      
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo Build completed on `date`
      
  post_build:
    commands:
      - echo Build finished

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  
cache:
  paths:
    - 'node_modules/**/*'
