import { DocumentConfig } from "./document.types";

export const documentConfigs: DocumentConfig[] = [
  {
    id: "add-product",
    name: "Additions",
    description: "Request to add new products to an existing GSA contract",
    icon: "Plus",
    fields: [
      {
        id: "contractNumber",
        label: "Contract Number",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
        width: "w-full",
      },
      {
        id: "salutation",
        label: "Salutation",
        type: "select",
        behavior: "manual",
        section: "Contract Information",
        options: [
          { value: "Mr.", label: "Mr." },
          { value: "Ms.", label: "Ms." },
          { value: "Mrs.", label: "Mrs." },
        ],
        validation: [{ type: "required", message: "Required" }],
        width: "w-1/4"
      },
      {
        id: "contractorName",
        label: "Contracting Officer",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
        width: "w-3/4"
      },
      {
        id: "companyName",
        label: "Company Name",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
      },
      {
        id: "sin",
        label: "SIN (Special Item Number)",
        type: "text",
        behavior: "editable",
        section: "Contract Information",
        validation: [{ type: "required", message: "Required" }],
      },

      {
        id: "gsaOfficeAddressLine",
        label: "GSA Office Address Line",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeCity",
        label: "GSA Office City",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeState",
        label: "GSA Office State",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeZip",
        label: "GSA Office ZIP Code",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },

      {
        id: "coo",
        label: "Country of Origin",
        type: "text",
        behavior: "manual",
        section: "Pricing & Discounts",
      },
      {
        id: "basicDiscount",
        label: "GSA Basic Discount",
        type: "text",
        behavior: "manual",
        section: "Pricing & Discounts",
      },
      {
        id: "numberOfProductsAdded",
        label: "Number of Products Added",
        type: "number",
        behavior: "readonly",
        section: "Pricing & Discounts",
      },
      {
        id: "quantityVolumeDiscount",
        label: "Quantity / Volume Discount",
        type: "text",
        behavior: "readonly",
        section: "Pricing & Discounts",
      },
      {
        id: "otherDiscounts",
        label: "Other Discounts / Concessions",
        type: "text",
        behavior: "readonly",
        section: "Pricing & Discounts",
      },

      {
        id: "deliveryAroNormal",
        label: "Delivery ARO – Normal",
        type: "text",
        behavior: "readonly",
        section: "Delivery Information",
      },
      {
        id: "deliveryAroExpedited",
        label: "Delivery ARO – Expedited",
        type: "text",
        behavior: "readonly",
        section: "Delivery Information",
      },
      {
        id: "fobTerms",
        label: "FOB Terms",
        type: "text",
        behavior: "readonly",
        section: "Delivery Information",
      },

      {
        id: "solicitationNumber",
        label: "Solicitation Number",
        type: "text",
        behavior: "manual",
        section: "Additional Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "refresh",
        label: "Refresh Number",
        type: "text",
        behavior: "manual",
        section: "Additional Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "additionRationale",
        label: "Addition Rationale",
        type: "textarea",
        behavior: "manual",
        section: "Additional Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "energyStarCompliance",
        label: "Energy Star Compliance",
        type: "select",
        behavior: "readonly",
        section: "Compliance",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
          { value: "na", label: "Not Applicable" },
        ],
      },


      {
        id: "consultantName",
        label: "Consultant Name",
        type: "text",
        behavior: "readonly",
        section: "Consultant Information",
      },
      {
        id: "consultantEmail",
        label: "Consultant Email",
        type: "email",
        behavior: "readonly",
        section: "Consultant Information",
      },
      {
        id: "consultantPhone",
        label: "Consultant Phone",
        type: "text",
        behavior: "manual",
        section: "Consultant Information",
        validation: [{ type: "required", message: "Required" }],

      },
    ],
  },
  {
    id: "delete-product",
    name: "Deletions",
    description: "Request to remove products from an existing GSA contract",
    icon: "Trash2",
    fields: [
      {
        id: "contractNumber",
        label: "Contract Number",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
        width: "w-full",
      },
      {
        id: "salutation",
        label: "Salutation",
        type: "select",
        behavior: "manual",
        section: "Contract Information",
        options: [
          { value: "Mr.", label: "Mr." },
          { value: "Ms.", label: "Ms." },
          { value: "Mrs.", label: "Mrs." },
        ],
        validation: [{ type: "required", message: "Required" }],
        width: "w-1/4"
      },
      {
        id: "contractorName",
        label: "Contracting Officer",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
        width: "w-3/4"
      },
      {
        id: "companyName",
        label: "Company Name",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
      },
      {
        id: "sin",
        label: "SIN (Special Item Number)",
        type: "text",
        behavior: "manual",
        section: "Contract Information",
        validation: [{ type: "required", message: "Required" }],

      },

      {
        id: "gsaOfficeAddressLine",
        label: "GSA Office Address Line",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeCity",
        label: "GSA Office City",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeState",
        label: "GSA Office State",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeZip",
        label: "GSA Office ZIP Code",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },

      {
        id: "deletionRationale",
        label: "Deletional Rationale",
        type: "textarea",
        behavior: "manual",
        section: "Additional Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "numberOfProductsDeleted",
        label: "Number of Products Deleted",
        type: "number",
        behavior: "readonly",
        section: "Pricing & Discounts",
      },

      {
        id: "consultantName",
        label: "Consultant Name",
        type: "text",
        behavior: "readonly",
        section: "Consultant Information",
      },
      {
        id: "consultantEmail",
        label: "Consultant Email",
        type: "email",
        behavior: "readonly",
        section: "Consultant Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "consultantPhone",
        label: "Consultant Phone",
        type: "text",
        behavior: "readonly",
        section: "Consultant Information",
        validation: [{ type: "required", message: "Required" }],
      },
    ],
  },

  {
    id: "price-increase",
    name: "Price Increase",
    description:
      "Economic Price Adjustment for price increases based on index changes",
    icon: "TrendingUp",
    fields: [
      {
        id: "contractNumber",
        label: "Contract Number",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
        width: "w-full",
      },
      {
        id: "salutation",
        label: "Salutation",
        type: "select",
        behavior: "manual",
        section: "Contract Information",
        options: [
          { value: "Mr.", label: "Mr." },
          { value: "Ms.", label: "Ms." },
          { value: "Mrs.", label: "Mrs." },
        ],
        validation: [{ type: "required", message: "Required" }],
        width: "w-1/4"
      },
      {
        id: "contractorName",
        label: "Contractor Name",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
        width: "w-3/4"
      },
      {
        id: "companyName",
        label: "Company Name",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
      },
      {
        id: "sin",
        label: "SIN",
        type: "text",
        behavior: "manual",
        section: "Contract Information",
        validation: [{ type: "required", message: "Required" }],

      },
      {
        id: "gsaOfficeAddressLine",
        label: "GSA Office Address Line",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeCity",
        label: "GSA Office City",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeState",
        label: "GSA Office State",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeZip",
        label: "GSA Office ZIP Code",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },

      {
        id: "increaseRationale",
        label: "Increase Rationale",
        type: "textarea",
        behavior: "manual",
        section: "Additional Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "requestedIncrease",
        label: "Requested Increase (%)",
        type: "percentage",
        behavior: "manual",
        section: "Price Adjustment",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "consultantName",
        label: "Consultant Name",
        type: "text",
        behavior: "readonly",
        section: "Consultant Information",
      },
      {
        id: "consultantEmail",
        label: "Consultant Email",
        type: "email",
        behavior: "readonly",
        section: "Consultant Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "consultantPhone",
        label: "Consultant Phone",
        type: "text",
        behavior: "readonly",
        section: "Consultant Information",
        validation: [{ type: "required", message: "Required" }],
      },
    ],
  },
  {
    id: "decrease-decrease",
    name: "Price Decrease",
    description:
      "Economic Price Adjustment for price decreases based on index changes",
    icon: "TrendingDown",
    fields: [
      {
        id: "contractNumber",
        label: "Contract Number",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
        width: "w-full",
      },
      {
        id: "salutation",
        label: "Salutation",
        type: "select",
        behavior: "manual",
        section: "Contract Information",
        options: [
          { value: "Mr.", label: "Mr." },
          { value: "Ms.", label: "Ms." },
          { value: "Mrs.", label: "Mrs." },
        ],
        validation: [{ type: "required", message: "Required" }],
        width: "w-1/4"
      },
      {
        id: "contractorName",
        label: "Contractor Name",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
        width: "w-3/4"
      },
      {
        id: "companyName",
        label: "Company Name",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
      },
      {
        id: "sin",
        label: "SIN",
        type: "text",
        behavior: "manual",
        section: "Contract Information",
        validation: [{ type: "required", message: "Required" }],

      },
      {
        id: "gsaOfficeAddressLine",
        label: "GSA Office Address Line",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeCity",
        label: "GSA Office City",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeState",
        label: "GSA Office State",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeZip",
        label: "GSA Office ZIP Code",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },

      {
        id: "decreaseRationale",
        label: "Decrease Rationale",
        type: "textarea",
        behavior: "manual",
        section: "Additional Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "requestedDecrease",
        label: "Requested Decrease (%)",
        type: "percentage",
        behavior: "manual",
        section: "Price Adjustment",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "consultantName",
        label: "Consultant Name",
        type: "text",
        behavior: "readonly",
        section: "Consultant Information",
      },
      {
        id: "consultantEmail",
        label: "Consultant Email",
        type: "email",
        behavior: "readonly",
        section: "Consultant Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "consultantPhone",
        label: "Consultant Phone",
        type: "text",
        behavior: "readonly",
        section: "Consultant Information",
        validation: [{ type: "required", message: "Required" }],
      },
    ],
  },
  {
    id: "description-change",
    name: "Description Changes",
    description: "Request to modify product descriptions without price changes",
    icon: "FileEdit",
    fields: [
      {
        id: "contractNumber",
        label: "Contract Number",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
        width: "w-full",
      },
      {
        id: "salutation",
        label: "Salutation",
        type: "select",
        behavior: "manual",
        section: "Contract Information",
        options: [
          { value: "Mr.", label: "Mr." },
          { value: "Ms.", label: "Ms." },
          { value: "Mrs.", label: "Mrs." },
        ],
        validation: [{ type: "required", message: "Required" }],
        width: "w-1/4"
      },
      {
        id: "contractorName",
        label: "Contractor Name",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
        width: "w-3/4"
      },
      {
        id: "companyName",
        label: "Company Name",
        type: "text",
        behavior: "readonly",
        section: "Contract Information",
      },
      {
        id: "sin",
        label: "SIN",
        type: "text",
        behavior: "editable",
        section: "Contract Information",
      },

      {
        id: "gsaOfficeAddressLine",
        label: "GSA Office Address Line",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeCity",
        label: "GSA Office City",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeState",
        label: "GSA Office State",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "gsaOfficeZip",
        label: "GSA Office ZIP Code",
        type: "text",
        behavior: "manual",
        section: "GSA Office Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "modificationRationale",
        label: "Description Change Rationale",
        type: "textarea",
        behavior: "manual",
        section: "Additional Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "descriptionChanged",
        label: "Number of Products Changed",
        type: "number",
        behavior: "readonly",
        section: "Pricing & Discounts",
      },

      {
        id: "consultantName",
        label: "Consultant Name",
        type: "text",
        behavior: "readonly",
        section: "Consultant Information",
      },
      {
        id: "consultantEmail",
        label: "Consultant Email",
        type: "email",
        behavior: "readonly",
        section: "Consultant Information",
        validation: [{ type: "required", message: "Required" }],
      },
      {
        id: "consultantPhone",
        label: "Consultant Phone",
        type: "text",
        behavior: "readonly",
        section: "Consultant Information",
        validation: [{ type: "required", message: "Required" }],
      },
    ],
  },
];

export const getDocumentConfig = (id: string): DocumentConfig | undefined => {
  return documentConfigs.find((config) => config.id === id);
};
